### ISSUE TITLE
Loss prevention: create repository with basic object tracking with region of interest

### ISSUE THREAD

**Issue by seanohair22** [intel-retail/loss-prevention#4]
- [x] Update to Yolov8
- [x] Create LP pipeline with object detection, object tracking, and ROI. @antoniomtz 
- [x] Update make files
- [x] Add integration tests
- [ ] Update documentation

**Comment by seanohair22** [comment]
DLStreamer: gvadetect element: inference-region parameter

**Comment by antoniomtz** [comment]
There is a new element in the latest version 2024.2.1 for ROI: 

https://github.com/dlstreamer/dlstreamer/blob/6a9a405ff45200cb5883614f496027a36b04cfd7/samples/gstreamer/gst_launch/gvaattachroi/README.md
